name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      APPLICATION_NAME: evil-trivia-boss
      ENVIRONMENT_NAME: Evil-trivia-boss-env
      DEPLOY_ZIP: deploy.zip
      S3_BUCKET: marginal-productions-test # 👈 create this bucket first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: .
        run: npm ci

      - name: Build backend
        working-directory: .
        run: npm run build

      - name: Copy frontend build to backend dist/public
        run: |
          mkdir -p dist/public
          cp -r frontend/dist/* dist/public/

      - name: Zip backend dist for deployment
        run: |
          cd dist
          zip -r ../${{ env.DEPLOY_ZIP }} .

      # ✅ Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::479166146426:user/github-beanstalk
          aws-region: ${{ env.AWS_REGION }}

      # ✅ Upload deployment package to S3
      - name: Upload deployment package to S3
        run: |
          aws s3 cp ${{ env.DEPLOY_ZIP }} s3://${{ env.S3_BUCKET }}/deployments/${{ github.sha }}.zip

      # ✅ Create new application version
      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.APPLICATION_NAME }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=${{ env.S3_BUCKET }},S3Key=deployments/${{ github.sha }}.zip \
            --region ${{ env.AWS_REGION }}

      # ✅ Update Elastic Beanstalk environment
      - name: Update Elastic Beanstalk environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.ENVIRONMENT_NAME }} \
            --version-label ${{ github.sha }} \
            --region ${{ env.AWS_REGION }}
